# SPDX-FileCopyrightText: 2026 Colin Edward Wood and contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

global:
  scrape_interval: 5s
scrape_configs:
  - job_name: receiver
    static_configs:
      - targets: ["receiver:8080"]
    metrics_path: /metrics
